# Generated by Django 3.2.4 on 2021-06-20 10:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Claim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=122)),
                ('email', models.CharField(default='', max_length=122)),
                ('mob', models.CharField(default='', max_length=122)),
                ('vehicle_year_make', models.DateField(default=datetime.datetime(2021, 6, 20, 10, 3, 14, 499197))),
                ('vehicle_model', models.CharField(default='', max_length=122)),
                ('vehicle_no', models.CharField(default='', max_length=122)),
                ('accident_time', models.DateTimeField(default=datetime.datetime(2021, 6, 20, 10, 3, 14, 499265))),
                ('location_of_loss', models.CharField(default='', max_length=122)),
                ('type_of_loss', models.CharField(default='', max_length=122)),
                ('description_of_loss', models.TextField(default='', max_length=122)),
                ('policy_report_lodge', models.CharField(default='', max_length=122)),
                ('any_body_injured', models.CharField(default='', max_length=122)),
                ('loss_image', models.ImageField(blank=True, null=True, upload_to='images/%Y/%m/%d')),
                ('docfile', models.FileField(blank=True, null=True, upload_to='documents/%Y/%m/%d')),
                ('approve', models.IntegerField(default=0)),
            ],
        ),
    ]
